# -*- coding: utf-8 -*-
"""Model_Final_Soil.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T7vq3NUGpLYkQUn5YmVF06UIC2fsilBB
"""

import joblib
import pandas as pd

model = joblib.load("soil_model.pkl")
scaler = joblib.load("scaler.pkl")

#features = ['moisture','ec',	'ph',	'salinity',	'tds']
sensor_input = pd.DataFrame([{
    "moisture": 35,
    "ec": 1.2,
    "ph": 6.8,
    "salinity": 0.3,
    "tds": 600,

}])

prediction = model.predict(sensor_input)


if prediction[0] == 0:
    prediction = "Saline Soil"
elif prediction[0] == 1:
    prediction = "Balanced Soil"
elif prediction[0] == 2:
    prediction = "Dry Soil"
elif prediction[0] == 3:
    prediction = "Acidic Soil"
print("Soil Class:", prediction)